"""log table

Revision ID: 7c3b7ff6926a
Revises: 59ea26e6c765
Create Date: 2025-08-03 12:50:56.874824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c3b7ff6926a'
down_revision: Union[str, Sequence[str], None] = '59ea26e6c765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.String(length=19), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    # ### end Alembic commands ###
