"""upgrade table

Revision ID: 95f9a1a5245b
Revises: 97c5682960de
Create Date: 2025-08-03 13:39:38.208552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f9a1a5245b'
down_revision: Union[str, Sequence[str], None] = '97c5682960de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs_api', sa.Column('method', sa.String(length=10), nullable=True))
    op.add_column('logs_api', sa.Column('latency', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs_api', 'latency')
    op.drop_column('logs_api', 'method')
    # ### end Alembic commands ###
