"""log table

Revision ID: 97c5682960de
Revises: 7c3b7ff6926a
Create Date: 2025-08-03 12:56:31.720402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97c5682960de'
down_revision: Union[str, Sequence[str], None] = '7c3b7ff6926a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs_api',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.String(length=19), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('time', sa.VARCHAR(length=19), nullable=False),
    sa.Column('status_code', sa.INTEGER(), nullable=True),
    sa.Column('endpoint', sa.VARCHAR(length=255), nullable=True),
    sa.Column('message', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('logs_api')
    # ### end Alembic commands ###
