"""scraping_requests

Revision ID: 9d981df615bd
Revises: abc3a9ff1545
Create Date: 2025-08-03 00:32:46.444897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d981df615bd'
down_revision: Union[str, Sequence[str], None] = 'abc3a9ff1545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraping_requests', sa.Column('trigger_by_user', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraping_requests', 'trigger_by_user')
    # ### end Alembic commands ###
