name: Flake8

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Run Flake8 and handle output
      id: flake8
      run: |
        flake8 $(git ls-files '*.py') > flake8-report.txt || true
    - name: Show Flake8 result
      run: |
        if [ -s flake8-report.txt ]; then
          echo "❌ Flake8 apontou os seguintes problemas:"
          cat flake8-report.txt
          exit 1
        else
          echo "✅ Flake8: Nenhum problema encontrado. Código conforme PEP8!"
        fi