name: PR Automático para main

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: Verificar código com Flake8
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: "3.11"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Run Flake8 and handle output
      id: flake8
      run: |
        flake8 $(git ls-files '*.py') > flake8-report.txt || true
    - name: Show Flake8 result
      run: |
        if [ -s flake8-report.txt ]; then
          echo "❌ Flake8 apontou os seguintes problemas:"
          cat flake8-report.txt
          exit 1
        else
          echo "✅ Flake8: Nenhum problema encontrado. Código conforme PEP8!"
        fi

  pull-request:
    name: Criar PR automático para main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: pull-request
        id: open-pr
        uses: diillson/auto-pull-request@v1.0.1
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: output-url
        run: echo ${{ steps.open-pr.outputs.pr_url }}

      - name: output-number
        run: echo ${{ steps.open-pr.outputs.pr_number }}

      - name: output-created
        run: echo ${{ steps.open-pr.outputs.pr_created }}

      - name: output-has-changed-files
        run: echo ${{ steps.open-pr.outputs.has_changed_files }}

      - name: Notificar conclusão
        run: echo "PR automático criado com sucesso para a branch main!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}