name: PR Automático para main

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: Verificar código com Flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurando Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Instalando dependências
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Executando Flake8
        id: flake8
        run: |
          flake8 $(git ls-files '*.py') > flake8-report.txt || true
      - name: Exibir resultado do Flake8
        run: |
          if [ -s flake8-report.txt ]; then
            echo "❌ Flake8 apontou os seguintes problemas:"
            cat flake8-report.txt
            exit 1
          else
            echo "✅ Flake8: Nenhum problema encontrado. Código conforme PEP8!"
          fi

  pull-request:
    name: Criar PR automático para main
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request to main
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'chore: open PR to main'
          branch: ${{ github.ref_name }}
          title: 'Auto PR - Merge ${{ github.ref_name }} into main'
          body: |
            Este PR foi criado automaticamente para merge do branch `${{ github.ref_name }}` para `main`.
          base: main
          delete-branch: false